//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCE.MainGear.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class BTOItem
    {
        public long BTOItemID { get; set; }
        public string ProductTitle { get; set; }
        public string Brand { get; set; }
        public string WebPrice { get; set; }
        public string PartNo { get; set; }
        public string ManufacturerPartNo { get; set; }
        public string GeneralImage { get; set; }
        public string ApplicationSpecificImage { get; set; }
        public string MainCategory { get; set; }
        public string SubCategory { get; set; }
        public string SectionCategory { get; set; }
        public string Description { get; set; }
        public string Specification { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public bool IsActive { get; set; }
        public string ProductID { get; set; }
        public string PrimaryOptionTitle { get; set; }
        public string PrimaryOptionValue { get; set; }
    }
}
