//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCE.MainGear.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemFilter
    {
        public long ItemFilterID { get; set; }
        public long SectionItemID { get; set; }
        public string SectionName { get; set; }
        public string Tag { get; set; }
        public string FilterType { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long CreatedBy { get; set; }
    }
}
