//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCE.MainGear.API
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MainGearWidgetEntities : DbContext
    {
        public MainGearWidgetEntities()
            : base("name=MainGearWidgetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminUser> AdminUsers { get; set; }
        public virtual DbSet<ItemFilter> ItemFilters { get; set; }
        public virtual DbSet<ItemTag> ItemTags { get; set; }
        public virtual DbSet<Pricing> Pricings { get; set; }
        public virtual DbSet<ProductInstruction> ProductInstructions { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductStep> ProductSteps { get; set; }
        public virtual DbSet<Recommendation> Recommendations { get; set; }
        public virtual DbSet<RenderMode> RenderModes { get; set; }
        public virtual DbSet<SectionInstruction> SectionInstructions { get; set; }
        public virtual DbSet<SectionItem> SectionItems { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<SubSection> SubSections { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<Wholesale> Wholesales { get; set; }
        public virtual DbSet<ProductOrder> ProductOrders { get; set; }
        public virtual DbSet<OrderItem> OrderItems { get; set; }
        public virtual DbSet<BTOItem> BTOItems { get; set; }
        public virtual DbSet<SectionItemOption> SectionItemOptions { get; set; }
    }
}
