//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCE.MainGear.API
{
    using System;
    using System.Collections.Generic;
    using SCE.MainGear.API.Models;
    
    public partial class SectionItem
    {
        public long SectionItemID { get; set; }
        public long BTOItemID { get; set; }
        public long WholesaleID { get; set; }
        public long SubSectionID { get; set; }
        public long DisplayOrder { get; set; }
        public string DisplayMode { get; set; }
        public int ProcessingTime { get; set; }
        public int RecommendationID { get; set; }
        public bool IsQuantity { get; set; }
        public bool IsQuantityRequired { get; set; }
        public int QuantityIncrement { get; set; }
        public bool IsDefault { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<bool> IsMaster { get; set; }
        public string TagText { get; set; }

        public List<ItemFilter> ItemFilters = new List<ItemFilter>();
        public List<ItemTag> ItemTags = new List<ItemTag>();

        public List<SectionItemOptionViewModel> Options = new List<SectionItemOptionViewModel>();

        public Wholesale WholeSale { get; set; }
        public BTOItem BTOItem { get; set; }
    }
}
