//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCE.MainGear.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public long SectionID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ImageName { get; set; }
        public long ProductID { get; set; }
        public int PricingID { get; set; }
        public long ProductStepID { get; set; }
        public int RenderModeID { get; set; }
        public bool IsRequired { get; set; }
        public long DisplayOrder { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<bool> IsMaster { get; set; }

        public List<SubSection> SubSections = new List<SubSection>();
        public List<SectionInstruction> Instructions { get; set; }
    }
}
