//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCE.MainGear.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubSection
    {
        public long SubSectionID { get; set; }
        public string Title { get; set; }
        public long SectionID { get; set; }
        public long DisplayOrder { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsMaster { get; set; }

        public List<SectionItem> SubSectionItems = new List<SectionItem>();
    }
}
